CREATE TABLE measurements
(
    id                                 UUID             NOT NULL,
    timestamp                          TIMESTAMP WITHOUT TIME ZONE,
    voltage                            DOUBLE PRECISION NOT NULL,
    current                            DOUBLE PRECISION NOT NULL,
    power_active                       DOUBLE PRECISION NOT NULL,
    power_apparent                     DOUBLE PRECISION NOT NULL,
    power_reactive                     DOUBLE PRECISION NOT NULL,
    power_factor                       DOUBLE PRECISION NOT NULL,
    phase_angle                        DOUBLE PRECISION NOT NULL,
    frequency                          DOUBLE PRECISION NOT NULL,
    import_energy_active               DOUBLE PRECISION NOT NULL,
    export_energy_active               DOUBLE PRECISION NOT NULL,
    import_energy_reactive             DOUBLE PRECISION NOT NULL,
    export_energy_reactive             DOUBLE PRECISION NOT NULL,
    total_demand_power_active          DOUBLE PRECISION NOT NULL,
    maximum_total_demand_power_active  DOUBLE PRECISION NOT NULL,
    import_demand_power_active         DOUBLE PRECISION NOT NULL,
    maximum_import_demand_power_active DOUBLE PRECISION NOT NULL,
    export_demand_power_active         DOUBLE PRECISION NOT NULL,
    maximum_export_demand_power_active DOUBLE PRECISION NOT NULL,
    total_demand_current               DOUBLE PRECISION NOT NULL,
    maximum_total_demand_current       DOUBLE PRECISION NOT NULL,
    total_energy_active                DOUBLE PRECISION NOT NULL,
    total_energy_reactive              DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_measurements PRIMARY KEY (id)
);